# Generated by Django 3.2.19 on 2023-06-25 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(auto_now=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('completed_date', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, default='../default_post_bge1xm', null=True, upload_to='images/')),
                ('priority', models.CharField(choices=[('PRIORITY1', '1'), ('PRIORITY2', '2'), ('PRIORITY3', '3')], default='PRIORITY1', max_length=25)),
                ('task_status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('TODO', 'To Do'), ('INPROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='BACKLOG', max_length=25)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
